/**
 * Created by hzwukewei on 2017-5-26.
 */

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const PROJECT_LIST_SUCCESS = 'PROJECT_LIST_SUCCESS';
export const STUDY_LIST_SUCCESS = 'STUDY_LIST_SUCCESS';